name: 'Check if external data changed'
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  flathub-data-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/
      env:
        GITHUB_TOKEN: ${{ secrets.FLATHUBBOT_TOKEN }}
        MANIFEST: "org.kde.kdiff3.json"
