name: 'Check if external data changed'
on:
  schedule:
    - cron: '0 * * * *'
workflow_dispatch


jobs:
  flathub-data-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: flathub/actions/flathub-data-checker@master
      env:
        GITHUB_TOKEN: ${{ secrets.FLATHUBBOT_TOKEN }}
