name: 'Check if external data changed'
on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  flathub-data-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "true"
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.FLATHUBBOT_TOKEN }}
